repos:
  - repo: https://github.com/psf/black
    # currently stable=22.3.0
    rev: stable
    hooks:
      # If you want support for Jupyter Notebooks as well, then replace id: black with id: black-jupyter (though note that it’s only available from version 21.8b0 onwards)
      - id: black-jupyter
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
