version: 2.1
jobs:
  # running commands on a basic image
  Pytest:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: 
          name: Python Version
          command: python --version
      - run:
          name: Change Directory
          command: |
            cd ./tests
            ls