# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# setting a working directory for different individual steps will be relative to the top-level directory; therefore, we can change the directory to tests/ in one step, and then change the directory to src/ in the next step, with both of these being relative to the top-level directory
# source: https://circleci.com/blog/decrease-your-build-times-by-running-jobs-in-parallel-with-workflows/
aliases:
    - &run_steps
      - checkout # pulls source code to the working directory
      - run: 
          name: Python Version
          command: python --version
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps2-{{ checksum "requirements.txt" }}
      # python -m pip install --upgrade pip
      #  python3 -m venv venv
      # . venv/bin/activate
      # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: # install and activate virtual environment with pip
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
      - run:
          name: Lint with flake8
          # stop the build if there are Python syntax errors or undefined names
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
          command: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     # if you "cd" in different runs, each will be relative to the top-level directory
      - run:
          name: Run Pytest
          command: |
            cd ./tests
            bash run_tests.sh
      - run:
          name: Run spaceship_titanic package
          command: |
            cd ./src
            python -m spaceship_titanic
      - run:
          name: Run spaceship_titanic package with XGBoost only
          command: |
            cd ./src
            python -m spaceship_titanic -xgb


version: 2.1
jobs:
  test:
    parameters:
      py:
        type: string
    docker:
      - image: cimg/python:<< parameters.py >>
    steps: # a collection of executable commands making up the 'build' job
      *run_steps

# matrix jobs: https://circleci.com/docs/2.0/using-matrix-jobs
# matrix jobs: https://circleci.com/blog/circleci-matrix-jobs/
# passing parameters to jobs: https://circleci.com/docs/2.0/jobs-steps#passing-parameters-to-jobs
workflows:
  build-python-versions:
    jobs:
      - test:
          matrix:
            parameters:
              py: ["3.9", "3.10"]






# source: https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml
# jobs:
#   # this needs to be named build; otherwise, need to create a workflow
#   "python_3-8":
#     docker:
#       - image: cimg/python:3.8
#     steps:
#       *run_steps
    
#   "python_3-9":
#     docker:
#       - image: cimg/python:3.9
#     steps:
#       *run_steps

#   "python_3-10":
#     docker:
#       - image: cimg/python:3.10
#     steps:
#       *run_steps

# # this is running jobs concurrently to save time
# workflows:
#   build-python-versions:
#     jobs:
#       - "python_3-8"
#       - "python_3-9"
#       - "python_3-10"

# version: 2.1
# jobs:
#   # this needs to be named build; otherwise, need to create a workflow
#   build:
#     docker:
#       - image: cimg/python:3.10.4
#     steps:
#       - checkout
#       - run: 
#           name: Python Version
#           command: python --version
#       - run:
#           name: Install dependencies
#           command: |
#             python -m pip install --upgrade pip
#             python -m pip install flake8 pytest
#             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#       - run:
#           name: Lint with flake8
#           # stop the build if there are Python syntax errors or undefined names
#           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
#           command: |
#             flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#             flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      # if you "cd" in different runs, each will be relative to the top-level directory
#       - run:
#           name: Run Pytest
#           command: |
#             cd ./tests
#             bash run_tests.sh
#       - run:
#           name: Run spaceship_titanic package
#           command: |
#             cd ./src
#             python -m spaceship_titanic


#   Hello-World:
#     docker:
#       - image: cimg/base:2021.04
#     steps:
#       - run:
#           name: Saying Hello
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'
#   # fetching code from the repo
#   Fetch-Code:
#     docker:
#       - image: cimg/base:2021.04
#     steps:
#       - checkout
#       - run:
#           name: Getting the Code
#           command: |
#             ls -al
#             echo '^^^Your repo files^^^'
#   # running a node container
#   Using-Node:
#     docker:
#       - image: cimg/node:17.2
#     steps:
#       - run:
#           name: Running the Node Container
#           command: |
#             node -v
# workflows:
#   Example-Workflow:
#     jobs:
#       - Hello-World
#       - Fetch-Code:
#           requires:
#             - Hello-World
#       - Using-Node:
#           requires:
#             - Fetch-Code