# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# setting a working directory for different individual steps will be relative to the top-level directory; therefore, we can change the directory to tests/ in one step, and then change the directory to src/ in the next step, with both of these being relative to the top-level directory
# source: https://circleci.com/blog/decrease-your-build-times-by-running-jobs-in-parallel-with-workflows/
aliases:
    - &run_steps
      - checkout # pulls source code to the working directory
      - run: 
          name: Python Version
          command: python --version
      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: deps1-{{ checksum "requirements.txt" }}
      # source: https://circleci.com/docs/2.0/caching#restoring-cache
      # source: https://gist.github.com/eddiewebb/ea07f681688a61d046e42619af31bbe6
      # source: https://circleci.com/docs/2.0/caching-strategy#pip-python
      # source: https://pipenv-fork.readthedocs.io/en/latest/diagnose.html
      # source: https://gist.github.com/toransahu/c9769fb1e645fbf17635e1b49f4c5d95
      # can perform better caching by placing the virtual environment in the current directory and caching from there
      - run: # install pipenv and the deterministic builds
          name: Install dependencies
          command: |
            pip install --no-cache-dir --upgrade pip && pip install pipenv
            pipenv sync
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pipenv" # default cache directory for pipenv with Unix systems
      - run:
          name: Lint with flake8
          # stop the build if there are Python syntax errors or undefined names
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # pipenv run will run a given command from the virtualenv, with any arguments forwarded 
          command: |
            pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     # if you "cd" in different runs, each will be relative to the top-level directory
      - run:
          name: Run Pytest
          command: |
            bash run_test_suite.sh
      - run:
          name: Run spaceship_titanic package
          command: |
            bash run_spaceship_titanic.sh
      - run:
          name: Run spaceship_titanic package with XGBoost only
          command: |
            bash run_spaceship_titanic_xgboost_only.sh


# this was using just pip rather than pipenv; was about 20-30 seconds faster, but this may be due to poor caching with pipenv

# aliases:
#     - &run_steps
#       - checkout # pulls source code to the working directory
#       - run: 
#           name: Python Version
#           command: python --version
#       - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
#           key: deps2-{{ checksum "requirements.txt" }}
#       # source: https://circleci.com/docs/2.0/caching#restoring-cache
#       # source: https://gist.github.com/eddiewebb/ea07f681688a61d046e42619af31bbe6
#       - run: # install and activate virtual environment with pip
#           name: Install dependencies
#           command: |
#             python -m pip install --upgrade pip
#             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#       - save_cache:
#           key: deps2-{{ checksum "requirements.txt" }}
#           paths:
#             - "~/.cache/pip" # default cache directory for pip with Unix systems
#       - run:
#           name: Lint with flake8
#           # stop the build if there are Python syntax errors or undefined names
#           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
#           command: |
#             flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#             flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      # if you "cd" in different runs, each will be relative to the top-level directory
#       - run:
#           name: Run Pytest
#           command: |
#             cd ./tests
#             bash run_tests.sh
#       - run:
#           name: Run spaceship_titanic package
#           command: |
#             cd ./src
#             python -m spaceship_titanic
#       - run:
#           name: Run spaceship_titanic package with XGBoost only
#           command: |
#             cd ./src
#             python -m spaceship_titanic -xgb


version: 2.1
jobs:
  test:
    parameters:
      py:
        type: string
    docker:
      - image: cimg/python:<< parameters.py >>
    steps: # a collection of executable commands making up the 'build' job
      *run_steps

# matrix jobs: https://circleci.com/docs/2.0/using-matrix-jobs
# matrix jobs: https://circleci.com/blog/circleci-matrix-jobs/
# passing parameters to jobs: https://circleci.com/docs/2.0/jobs-steps#passing-parameters-to-jobs
workflows:
  build-python-versions:
    jobs:
      - test:
          matrix:
            parameters:
              py: ["3.9", "3.10"]




# below is the initial iteration of workflows before using matrix jobs

# source: https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml
# source: https://circleci.com/docs/2.0/config-intro
# jobs:
#   # this needs to be named build; otherwise, need to create a workflow
#   "python_3-8":
#     docker:
#       - image: cimg/python:3.8
#     steps:
#       *run_steps
    
#   "python_3-9":
#     docker:
#       - image: cimg/python:3.9
#     steps:
#       *run_steps

#   "python_3-10":
#     docker:
#       - image: cimg/python:3.10
#     steps:
#       *run_steps

# # this is running jobs concurrently to save time
# workflows:
#   build-python-versions:
#     jobs:
#       - "python_3-8"
#       - "python_3-9"
#       - "python_3-10"